# Generated by Django 3.2 on 2022-04-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageseo',
            options={'verbose_name': 'Home Page SEO', 'verbose_name_plural': 'Home Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='homepageseotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Home Page SEO Translation'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Home Slider', 'verbose_name_plural': 'Home Sliders'},
        ),
        migrations.AlterModelOptions(
            name='homeslidertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Home Slider Translation'},
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homeslider', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homeslidertranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homeslidertranslation',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='homeslidertranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
