# Generated by Django 3.2 on 2022-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_servicecategory_in_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='before_after', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Before & After Image',
                'verbose_name_plural': 'Before & After Images',
            },
        ),
    ]
