# Generated by Django 3.2 on 2022-04-03 18:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_beforeafterimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Banner Image')),
                ('meta_keywords', models.ManyToManyField(blank=True, to='page.Keywords', verbose_name='Meta Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'About Page SEO',
                'verbose_name_plural': 'About Page SEO',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPageSeoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('banner_description', models.TextField(blank=True, null=True, verbose_name='Banner Description')),
                ('content_title1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Content Title 1')),
                ('content_body1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content Body 1')),
                ('content_title2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Content Title 2')),
                ('content_body2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content Body 2')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.aboutpageseo')),
            ],
            options={
                'verbose_name': 'About Page SEO Translation',
                'db_table': 'page_aboutpageseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
