# Generated by Django 3.2 on 2022-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_aboutpageseo_aboutpageseotranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageseo',
            name='content_image1',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Content Image 1'),
        ),
        migrations.AddField(
            model_name='aboutpageseo',
            name='content_image2',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Content Image 2'),
        ),
        migrations.AlterField(
            model_name='aboutpageseo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/banner', verbose_name='Banner Image'),
        ),
    ]
