# Generated by Django 3.2 on 2022-04-15 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_gdprpageseo_gdprpageseotranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpageseotranslation',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Banner Description'),
        ),
    ]
