# Generated by Django 3.2 on 2022-04-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20220415_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Frequently Asked Question Translation'},
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.serviceitem', verbose_name='Related Service'),
        ),
    ]
