# Generated by Django 3.2 on 2022-09-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
        ('page', '0017_auto_20220430_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='appointmentpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='beforeafterpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='blogspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='contactpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='gdprpageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='homepageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='howitworkspageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
        migrations.AddField(
            model_name='servicespageseo',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='popup.popup', verbose_name='Popup'),
        ),
    ]
