from .common import *
from .home import *
from .services import *
from .before_after import *
from .about import *
from .faq import *
from .howitworks import *
from .blog import *
from .contact import *
from .appointment import *
from .gdpr import *
